### ISSUE TITLE
Saved filter doesn't reload show cables

### ISSUE THREAD

**Issue by fafavorit** [netbox-community/netbox-topology-views#236]
### NetBox version

v3.4.2

### Topology Views version

v3.2.0

### Steps to Reproduce

1. Create topology with enabled Show Cables
2. Save filter
3. Reload filter 

### Expected Behavior

I would expect to see connected devices as I had before saving filter.

### Observed Behavior

Devices are displayed without connection cables. In saved filter definition is "show_cables": [  "on"]

**Comment by dreng** [comment]
We have to check if this is an upstream bug with custom filter forms. Thanks for reporting!

**Comment by dreng** [comment]
I've had a sneak peek into the problem and I wonder if it's possible at all to integrate the checkboxes into the filterset without having a model for it. @mattieserver Can you answer that question?

In this case it is a somewhat bigger task and probably related to #78 .

**Comment by dreng** [comment]
Just for the record: I started a discussion at https://github.com/netbox-community/netbox/discussions/12397 regarding this issue but unfortunately I got no answer.
